# Generated by Django 6.0.3 on 2026-04-12 19:20

from django.db import migrations, models


def backfill_persian_content(apps, schema_editor):
    Category = apps.get_model("bookstore", "Category")
    Book = apps.get_model("bookstore", "Book")

    category_map = {
        "Classic Literature": "ادبیات کلاسیک",
        "Science Fiction": "علمی تخیلی",
        "Self Development": "خودسازی",
        "Business": "کسب‌وکار",
        "Technology": "فناوری",
        "History": "تاریخ",
    }
    for en_name, fa_name in category_map.items():
        Category.objects.filter(name=en_name, name_fa="").update(name_fa=fa_name)

    book_map = {
        "Pride and Prejudice": {
            "title_fa": "غرور و تعصب",
            "author_fa": "جین آستن",
            "description_fa": "داستانی عاشقانه و طنزی اجتماعی از انگلستان قرن نوزدهم.",
        },
        "Dune": {
            "title_fa": "تل‌ماسه",
            "author_fa": "فرانک هربرت",
            "description_fa": "روایتی حماسی از سیاست، پیشگویی و بقا در سیاره آراکیس.",
        },
        "Atomic Habits": {
            "title_fa": "عادت‌های اتمی",
            "author_fa": "جیمز کلیر",
            "description_fa": "راهبردهای کاربردی برای ساخت عادت‌های خوب و ترک عادت‌های بد.",
        },
        "The Lean Startup": {
            "title_fa": "استارتاپ ناب",
            "author_fa": "اریک ریس",
            "description_fa": "چارچوبی مدرن برای ساخت استارتاپ با آزمایش‌های سریع.",
        },
        "Clean Code": {
            "title_fa": "کدنویسی تمیز",
            "author_fa": "رابرت سی. مارتین",
            "description_fa": "راهنمایی کاربردی برای مهارت نرم‌افزاری و کدهای قابل نگهداری.",
        },
        "Sapiens": {
            "title_fa": "انسان خردمند",
            "author_fa": "یووال نوح هراری",
            "description_fa": "تاریخچه‌ای کوتاه از انسان از دوران باستان تا امروز.",
        },
    }
    for en_title, data in book_map.items():
        books = Book.objects.filter(title=en_title)
        for book in books:
            updates = {}
            if not book.title_fa:
                updates["title_fa"] = data["title_fa"]
            if not book.author_fa:
                updates["author_fa"] = data["author_fa"]
            if not book.description_fa:
                updates["description_fa"] = data["description_fa"]
            if updates:
                for field_name, value in updates.items():
                    setattr(book, field_name, value)
                book.save(update_fields=list(updates.keys()))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_bookdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_fa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='book',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(backfill_persian_content, noop_reverse),
    ]
