# Generated by Django 6.0.3 on 2026-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_author_fa_book_description_fa_book_title_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='book_covers/'),
        ),
    ]
